### ISSUE TITLE
The default value of the `date` argument will always remain the same as when the method was compiled.

### ISSUE THREAD

**Issue by o2bubble** [TheMultii/snowflake-util#1]
https://github.com/TheMultii/snowflake-util/blob/1b2de7e1b49096c21114f788fdb7447e0fea5de5/snowflake/snowflake.py#L375

```text
date: Optional[datetime]
            The date to use for the snowflake. If not provided, the current date will be used.
```
It doesn't match the description.

**Comment by TheMultii** [comment]
Hey, thanks for creating the issue. While using this code, I wasn't aware that the generation date was always the same. I have fixed this problem and the updated version of the code is now available on PyPI.

The code no longer uses the default value of `datetime.now()`.
