### ISSUE TITLE
Snowflake generation and parsing requires the epoch to be of class Snowflake.Epoch

### ISSUE THREAD

**Issue by infernostars** [TheMultii/snowflake-util#4]
## Description
Snowflake generation and parsing requires the epoch to be of class Snowflake.Epoch. This is due to [line 432](https://github.com/TheMultii/snowflake-util/blob/master/snowflake/snowflake.py#L432C60-L432C85) and [line 492](https://github.com/TheMultii/snowflake-util/blob/master/snowflake/snowflake.py#L492C59-L492C84) which gets the Epoch's value instead of checking for the class and only getting the value if it is an Epoch.
## Expected behavior
As the readme implies, using an integer for the epoch should work.
## Actual behavior
You either have to use a default epoch or set up a fake class for this.
## Temporary fixes
Making an Enum class and faking the class to be an Epoch class works:
```py
import snowflake

class Epoch(Enum):
    JAN_1_2024 = 1_704_067_200_000

    @property
    def __class__(self):
        # The code checks if the enum's value, which requires it to be an enum [obviously].
        # it also checks if it's a snowflake Epoch, so we need to fake it.
        return snowflake.Epoch

    # noinspection PyTypeChecker
    def __str__(self) -> int:
        # This is a part of the snowflake.Epoch enum, and returns an int. Very weird but technically defined behavior
        return self.name
```

**Comment by TheMultii** [comment]
Fixed on the master branch, I’ll publish it to PyPI soon.
